# Uncomment this line to define a global platform for your project
platform :ios, '10.0'

target 'iOSTrial&Error' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

pod 'UITextField+Shake', '~> 1.1'
# pods go here

  # Pods for iOSTrial&Error

end


