# Uncomment this line to define a global platform for your project
platform :ios, '9.3'

target 'iOSTrial&Error' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
pod 'paper-onboarding'

  # Pods for iOSTrial&Error

end
