# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-18 06:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('firstName', models.TextField(max_length=100)),
                ('lastName', models.TextField(max_length=100)),
                ('email', models.TextField()),
                ('phoneNumber', models.IntegerField()),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
