# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 23:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsModel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsmodel',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='newsmodel',
            name='firstName',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='newsmodel',
            name='lastName',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='newsmodel',
            name='phoneNumber',
            field=models.CharField(default='', max_length=15),
        ),
    ]
